# SonarQube / SonarCloud Configuration
sonar.sonarQubeUri=https://sonarcloud.io
sonar.organization=FamilyOG
sonar.projectKey=FamilyOG_Babycharts
sonar.projectName=Babycharts
sonar.sources=src,server
sonar.exclusions=**/dist/**,**/node_modules/**,**/server/data/**,**/.github/**,**/*.yml,**/*.yaml
sonar.javascript.environments=browser,nodejs

