# SonarQube / SonarLint Configuration
sonar.projectKey=babycharts
sonar.projectName=BabyCharts
sonar.sources=src,server
sonar.exclusions=**/dist/**,**/node_modules/**,**/server/data/**
sonar.javascript.environments=browser,nodejs
