name: Dockerfile Lint

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**/Dockerfile'

  pull_request:
    paths:
      - 'Dockerfile'
      - '**/Dockerfile'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
