name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '41 2 * * 2'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-latest

    container:
      image: zricethezav/gitleaks:v8.24.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks CLI
        run: gitleaks detect --source=. --verbose --redact
