name: Semgrep Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '27 3 * * 3'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:1.155.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config auto \
            --sarif \
            --output semgrep.sarif \
            .

      - name: Upload SARIF report to GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        with:
          sarif_file: semgrep.sarif
          category: semgrep
